name: knowhen
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10
  smooth_page_indicator: ^1.2.0+3
  google_sign_in: ^6.2.2
  auto_route: ^9.3.0+1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  json_annotation: ^4.9.0
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  hugeicons: ^0.0.7
  shared_preferences: ^2.4.0
  envied: ^1.1.0
  fal_client: ^0.3.0
  http: ^1.3.0
  provider: ^6.1.2
  date_picker_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.3.1
  json_serializable: ^6.9.3
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/launcher/icon.png"
  adaptive_icon_background: "#14142B"
  adaptive_icon_foreground: "lib/assets/launcher/icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true

assets:
  - assets/
