on:
  push:
    branches:
      - main
      
name: Release Android apk

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          FAL_AI_API_KEY: ${{ secrets.FAL_AI_API_KEY }}
      - run: flutter clean
      - run: flutter pub get
      - run : dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1+1
          token: ${{ secrets.RELEASE_ACTION_SECRET }}
